
graph_data = {  'Addis Ababa': ['Adama', 'Ambo', 'Debre Berhan'],
                'Adama': ['Matahara', 'Asella', 'Batu', 'Addis Ababa'], 
                'Ambo': ['Wolkite', 'Addis Ababa', 'Nekemte'], 
                'Debre Berhan': ['Addis Ababa', 'Debre Sina'], 
                'Matahara': ['Adama', 'Awash'], 
                'Asella': ['Adama', 'Assasa'], 
                'Batu': ['Adama', 'Buta Jirra', 'Shashamene'], 
                'Wolkite': ['Ambo', 'Worabe', 'Jimma'], 
                'Nekemte': ['Ambo', 'Bedelle', 'Gimbi'], 
                'Debre Sina': ['Debre Berhan', 'Kemise', 'Debre Markos'], 
                'Awash': ['Chiro', 'Gobi Rasu', 'Matahara'], 
                'Assasa': ['Asella', 'Dodolla'], 
                'Buta Jirra': ['Batu', 'Worabe'], 
                'Shashamene': ['Batu', 'Hawassa', 'Dodolla', 'Hossana'], 
                'Worabe': ['Wolkite', 'Hossana', 'Buta Jirra'], 
                'Jimma': ['Wolkite', 'Bonga', 'Bedelle'], 
                'Bedelle': ['Nekemte', 'Gore', 'Jimma'], 
                'Gimbi': ['Nekemte', 'Dambidollo'], 
                'Kemise': ['Debre Sina', 'Dessie'], 
                'Debre Markos': ['Debre Sina', 'Finote Selam'],
                'Chiro': ['Awash', 'Dire Dawa'], 
                'Gobi Rasu': ['Awash', 'Samara'], 
                'Dodolla': ['Assasa', 'Shashamene', 'Bale'], 
                'Hawassa': ['Shashamene', 'Dilla'], 
                'Hossana': ['Shashamene', 'Worabe', 'Wolaita Sodo'], 
                'Bonga': ['Jimma', 'Dawro', 'Tepi', 'Mizan Teferi'], 
                'Gore': ['Tepi', 'Gambella', 'Bedelle'], 
                'Dambidollo': ['Gimbi', 'Assosa', 'Gambella'], 
                'Dessie': ['Kemise', 'Woldia'], 
                'Finote Selam': ['Debre Markos', 'Bahirdar', 'Injibara'], 
                'Dire Dawa': [ 'Chiro', 'Harar'], 
                'Samara': [ 'Gobi Rasu', 'Fanti Rasu', 'Alamata', 'Woldia'],
                'Bale': ['Liben', 'Dodolla', 'Goba', 'Sof Oumer'], 
                'Dilla': ['Hawassa', 'Bulehora'], 
                'Wolaita Sodo': ['Arba Minchi', 'Dawro', 'Hossana'], 
                'Dawro': [ 'Bonga', 'Basketo', 'Wolaita Sodo'], 
                'Tepi': ['Gore', 'Bonga', 'Mizan Teferi'], 
                'Mizan Teferi': ['Tepi', 'Bonga', 'Basketo'], 
                'Gambella': ['Gore', 'Dambidollo'], 
                'Assosa': ['Dambidollo', 'Metekel'], 
                'Woldia': ['Dessie', 'Lalibella', 'Samara', 'Alamata'],
                'Bahirdar': ['Finote Selam', 'Injibara', 'Metekel', 'Azezo', 'Debre Tabor'], 
                'Injibara': ['Bahirdar', 'Finote Selam'], 
                'Harar': [ 'Dire Dawa', 'Babile'], 
                'Fanti Rasu': ['Samara', 'Kilbet Rasu'], 
                'Alamata': ['Samara', 'Woldia', 'Mekelle', 'Sekota'], 
                'Liben': ['Bale'], 
                'Goba': ['Bale', 'Sof Oumer', 'Dega Habur'], 
                'Sof Oumer': ['Goba', 'Bale', 'Kebri Dehar'], 
                'Bulehora': [ 'Dilla', 'Yabello'], 
                'Arba Minchi': ['Wolaita Sodo', 'Konso', 'Basketo'], 
                'Basketo': [ 'Arba Minchi', 'Dawro', 'Mizan Teferi', 'Benchi Maji'], 
                'Metekel': [ 'Assosa', 'Bahirdar'],
                'Lalibella': ['Woldia', 'Debre Tabor', 'Sekota'],
                'Debre Tabor': ['Lalibella', 'Bahirdar'], 
                'Azezo': ['Gondar', 'Bahirdar', 'Metema'], 
                'Babile': [ 'Harar', 'Jigjiga'], 
                'Kilbet Rasu': ['Fanti Rasu' ], 
                'Mekelle': ['Alamata', 'Adwa', 'Adigrat', 'Sekota'], 
                'Sekota': ['Alamata', 'Mekelle', 'Lalibella'], 
                'Dega Habur': ['Goba', 'Jigjiga', 'Kebri Dehar'], 
                'Kebri Dehar': ['Gode', 'Sof Oumer', 'Dega Habur', 'Werdez'], 
                'Yabello': [ 'Bulehora', 'Konso', 'Moyale'], 
                'Konso': ['Arba Minchi', 'Yabello'], 
                'Benchi Maji': [ 'Basketo'], 
                'Gondar': [ 'Azezo', 'Metema', 'Debarke'],
                'Metema': [ 'Azezo', 'Gondar'],  
                'Jigjiga': [ 'Babile', 'Dega Habur'], 
                'Adwa': [ 'Mekelle', 'Axum', 'Adigrat'],
                'Adigrat': [ 'Mekelle', 'Adwa'], 
                'Gode': [ 'Dollo', 'Kebri Dehar' ], 
                'Werdez': [ 'Kebri Dehar'], 
                'Moyale': [ 'Yabello'], 
                'Debarke': [ 'Gondar', 'Shire'], 
                'Axum': ['Shire', 'Adwa'], 
                'Dollo': [ 'Gode'], 
                'Shire': [ 'Axum', 'Humera', 'Debarke'],
                'Humera': [ 'Shire', 'Gondar']}


# city_node_dict = {
#     'A': ['B', 'C', 'D'],
#     'B': ['E'],
#     'C': ['F', 'G'],
#     'D': ['H'],
#     'E': ['I'],
#     'F': [],
#     'G': ['J'],
#     'H': [],
#     'I': [],
#     'J': []
# }
# city_node_ucs = {
#     'A': [('B', 3), ('C', 5), ('D', 5)],
#     'B': [('E', 4)],
#     'C': [('F', 3), ('G', 2)],
#     'D': [('H', 4)],
#     'E': [('I', 5)],
#     'F': [],
#     'G': [('J', 6)],
#     'H': [],
#     'I': [],
#     'J': []
# }
city_node_ucs = {'Addis Ababa': [('Adama',3), ('Ambo',5), ('Debre Berhan',5)],
            'Adama': [('Matahara',3), ('Asella',4), ('Batu',4), ('Addis Ababa',3)], 
            'Ambo': [('Wolkite',6), ('Addis Ababa',9), ('Nekemte',5)], 
            'Debre Berhan': [('Addis Ababa',5), ('Debre Sina',2)], 
            'Matahara': [('Adama',3), ('Awash',1)], 
            'Asella': [('Adama',4), ('Assasa',4)], 
            'Batu': [('Adama',4), ('Buta Jirra',2), ('Shashamene',3)], 
            'Wolkite': [('Ambo',6), ('Worabe',5), ('Jimma',8)], 
            'Nekemte': [('Ambo',9), ('Bedelle',5), ('Gimbi',4)], 
            'Debre Sina': [('Debre Berhan',2), ('Kemise',6), ('Debre Markos',17)], 
            'Awash': [('Chiro',4), ('Gobi Rasu',5), ('Matahara',1)], 
            'Assasa': [('Asella',4), ('Dodolla',1)], 
            'Buta Jirra': [('Batu',2), ('Worabe',2)], 
            'Shashamene': [('Batu',3), ('Hawassa',1), ('Dodolla',3), ('Hossana',7)], 
            'Worabe': [('Wolkite',5), ('Hossana',2), ('Buta Jirra',2)], 
            'Jimma': [('Wolkite',8), ('Bonga',4), ('Bedelle',7)], 
            'Bedelle': [('Nekemte',5), ('Gore',6), ('Jimma',7)], 
            'Gimbi': [('Nekemte',4), ('Dambidollo',6)], 
            'Kemise': [('Debre Sina',6), ('Dessie',4)], 
            'Debre Markos': [('Debre Sina',17), ('Finote Selam',3)],
            'Chiro': [('Awash',4), ('Dire Dawa',8)], 
            'Gobi Rasu': [('Awash',5), ('Samara',9)], 
            'Dodolla': [('Assasa',1), ('Shashamene',3), ('Bale',13)], 
            'Hawassa': [('Shashamene',1), ('Dilla',3)], 
            'Hossana': [('Shashamene',7), ('Worabe',2), ('Wolaita Sodo',4)], 
            'Bonga': [('Jimma',4), ('Dawro',10), ('Tepi',8), ('Mizan Teferi',4)], 
            'Gore': [('Tepi',9), ('Gambella',5), ('Bedelle',6)], 
            'Dambidollo': [('Gimbi',6), ('Assosa',12), ('Gambella',4)], 
            'Dessie': [('Kemise',4), ('Woldia',6)], 
            'Finote Selam': [('Debre Markos',3),( 'Bahirdar',6), ('Injibara',2)], 
            'Dire Dawa': [ ('Chiro',8), ('Harar',4)], 
            'Samara': [ ('Gobi Rasu',9), ('Fanti Rasu',7), ('Alamata',11), ('Woldia',8)],
            'Bale': [('Liben',11), ('Dodolla',13), ('Goba',18), ('Sof Oumer',23)], 
            'Dilla': [('Hawassa',3), ('Bulehora',4)], 
            'Wolaita Sodo': [('Arba Minchi',5), ('Dawro',6), ('Hossana',4)], 
            'Dawro': [ ('Bonga',10), ('Wolaita Sodo',10)], 
            'Tepi': [('Gore',9), ('Bonga',8), ('Mizan Teferi',4)], 
            'Mizan Teferi': [('Tepi',4), ('Bonga',4)], 
            'Gambella': [('Gore',5), ('Dambidollo',4)], 
            'Assosa': [('Dambidollo',12)], 
            'Woldia': [('Dessie',6), ('Lalibella',7), ('Samara',8), ('Alamata',3)],
            'Bahirdar': [('Finote Selam',6), ('Injibara',4), ('Metekel',11), ('Azezo',7), ('Debre Tabor',4)], 
            'Injibara': [('Bahirdar',4), ('Finote Selam',2)], 
            'Harar': [ ('Dire Dawa',4), ('Babile',2)], 
            'Fanti Rasu': [('Samara',7), ('Kilbet Rasu',6)], 
            'Alamata': [('Samara',11), ('Woldia',3), ('Mekelle',5), ('Sekota',6)], 
            'Liben': [('Bale',11)], 
            'Goba': [('Bale',18), ('Sof Oumer',6), ('Babile',28)], 
            'Sof Oumer': [('Goba',6), ('Bale',23), ('Gode',23)], 
            'Bulehora': [('Dilla',4), ('Yabello',3)], 
            'Arba Minchi': [('Wolaita Sodo',5), ('Konso',4), ('Basketo',10)], 
            'Basketo': [ ('Arba Minchi',10), ('Benchi Maji',5)], 
            'Metekel': [('Bahirdar',11)],
            'Lalibella': [('Woldia',7), ('Debre Tabor',8), ('Sekota',6)],
            'Debre Tabor': [('Lalibella',8), ('Bahirdar',4)], 
            'Azezo': [('Gondar',1), ('Bahirdar',7), ('Metema',7)], 
            'Babile': [( 'Harar',2), ('Jigjiga',3),('Goba',28)], 
            'Kilbet Rasu': [('Fanti Rasu',6)], 
            'Mekelle': [('Alamata',5), ('Adwa',7), ('Adigrat',4),('Sekota',9)], 
            'Sekota': [('Alamata',6), ('Mekelle',9), ('Lalibella',6)], 
            'Dega Habur': [('Jigjiga',5), ('Kebri Dehar',6)], 
            'Kebri Dehar': [('Gode',5), ('Dega Habur',6), ('Werdez',6)], 
            'Yabello': [ ('Bulehora',3), ('Konso',3), ('Moyale',6)], 
            'Konso': [('Arba Minchi',4), ('Yabello',3)], 
            'Benchi Maji': [ ('Basketo',5)], 
            'Gondar': [ ('Azezo',1),( 'Humera',9), ('Metema',7), ('Debarke',4)],
            'Metema': [('Azezo',7), ('Gondar',7)],  
            'Jigjiga': [ ('Babile',3), ('Dega Habur',5)], 
            'Adwa': [ ('Mekelle',7), ('Axum',1), ('Adigrat',4)],
            'Adigrat': [ ('Mekelle',4), ('Adwa',4)], 
            'Gode': [ ('Dollo',17), ('Kebri Dehar',5), ('Sof Oumer',23) ], 
            'Werdez': [ ('Kebri Dehar',6)], 
            'Moyale': [ ('Yabello',6)], 
            'Debarke': [ ('Gondar',4), ('Shire',7)], 
            'Axum': [('Shire',2), ('Adwa',1)], 
            'Dollo': [ ('Gode',17)], 
            'Shire': [('Axum',2), ('Humera',8), ('Debarke',7)],
            'Humera': [('Shire',8), ('Gondar',9)]}


distances_cost = {'Addis Ababa': {'Adama':3, 'Ambo':5, 'Debre Berhan':5,'Debre Markos':13},
                'Adama': {'Matahara':3, 'Asella':4, 'Batu':4, 'Addis Ababa':3}, 
                'Ambo': {'Wolkite':6, 'Addis Ababa':5, 'Nekemte':8}, 
                'Debre Berhan': {'Addis Ababa':5, 'Debre Sina':2},
                'Debre Markos':{'Addis Ababa':13,'Debre Sina':17,'Finote Selam':3},
                'Matahara': {'Adama':3, 'Awash':1}, 
                'Asella': {'Adama':4, 'Assasa':4}, 
                'Batu': {'Adama':4, 'Buta Jirra':2, 'Shashamene':3}, 
                'Wolkite': {'Ambo':6, 'Worabe':5, 'Jimma':8,'Hossana':5,'Buta Jirra':4}, 
                'Nekemte': {'Ambo':9, 'Bedelle':5, 'Gimbi':4}, 
                'Debre Sina': {'Debre Berhan':2, 'Kemise':7, 'Debre Markos':17}, 
                'Finote Selam': {'Debre Markos':3, 'Bahirdar':6, 'Injibara':2},
                'Awash': {'Chiro':4, 'Gobi Rasu':5, 'Matahara':1}, 
                'Assasa': {'Asella':4, 'Dodolla':1}, 
                'Buta Jirra': {'Batu':2,'Wolkite':4, 'Worabe':2}, 
                'Shashamene': {'Batu':3,'Dodolla':3, 'Hawassa':1, 'Hossana':7,'Worabe':6}, 
                'Worabe': {'Wolkite':5, 'Hossana':2,'Shashamene':6, 'Buta Jirra':2}, 
                'Jimma': {'Wolkite':8, 'Bonga':4, 'Bedelle':7}, 
                'Hossana': {'Shashamene':7, 'Worabe':2, 'Wolkite':5, 'Wolaita Sodo':4}, 
                'Bedelle': {'Nekemte':5, 'Gore':6, 'Jimma':7}, 
                'Gimbi': {'Nekemte':4, 'Dambidollo':6,'Assosa':8}, 
                'Kemise': {'Debre Sina':6, 'Dessie':4}, 
                'Bahirdar': {'Finote Selam':6, 'Injibara':4, 'Metekel':11, 'Azezo':7, 'Debre Tabor':4},
                'Injibara': {'Bahirdar':4, 'Finote Selam':2},
                'Chiro': {'Awash':4, 'Dire Dawa':8}, 
                'Gobi Rasu': {'Awash':5, 'Samara':10}, 
                'Dodolla': {'Assasa':1, 'Shashamene':3, 'Robe':13}, 
                'Hawassa': {'Shashamene':1, 'Dilla':3}, 
                'Bonga': {'Jimma':4, 'Dawro':10, 'Tepi':8, 'Mizan Teferi':4}, 
                'Wolaita Sodo': {'Arba Minchi':4, 'Dawro':6, 'Hossana':4}, 
                'Gore': {'Tepi':9, 'Gambella':5, 'Bedelle':6}, 
                'Dambidollo': {'Gimbi':6, 'Assosa':12, 'Gambella':4}, 
                'Assosa': {'Gimbi':8, 'Dambidollo':12}, 
                'Dessie': {'Kemise':4, 'Woldia':6},
                'Metekel': { 'Bahirdar':11},
                'Azezo': {'Gondar':1, 'Bahirdar':7, 'Metema':7}, 
                'Debre Tabor': {'Lalibella':8, 'Gondar':6, 'Bahirdar':4},
                'Dire Dawa': { 'Chiro':8, 'Harar':4}, 
                'Samara': { 'Gobi Rasu':10, 'Fanti Rasu':7, 'Alamata':11, 'Woldia':8},
                'Robe': {'Liben':11, 'Dodolla':13, 'Goba':18, 'Sof Oumer':23}, 
                'Dilla': {'Hawassa':3, 'Bulehora':4}, 
                'Dawro': { 'Bonga':10, 'Wolaita Sodo':6}, 
                'Tepi': {'Gore':9, 'Bonga':8, 'Mizan Teferi':4}, 
                'Mizan Teferi': {'Tepi':4, 'Bonga':4}, 
                'Gambella': {'Gore':5, 'Dambidollo':4}, 
                'Arba Minchi': {'Wolaita Sodo':5, 'Konso':4, 'Basketo':10},
                'Woldia': {'Dessie':6, 'Lalibella':7, 'Samara':8, 'Alamata':3},
                'Gondar': { 'Azezo':1, 'Humera':9, 'Metema':7, 'Debarke':4,'Debre Tabor':6},
                'Metema': { 'Azezo':7, 'Gondar':7}, 
                'Lalibella': {'Woldia':7, 'Debre Tabor':8, 'Sekota':6},
                'Harar': { 'Dire Dawa':4, 'Babile':2}, 
                'Fanti Rasu': {'Samara':7, 'Kilbet Rasu':6}, 
                'Alamata': {'Samara':11, 'Woldia':3, 'Mekelle':5, 'Sekota':6}, 
                'Liben': {'Robe':11}, 
                'Goba': {'Robe':18, 'Sof Oumer':6, 'Babile':28}, 
                'Sof Oumer': {'Goba':6, 'Robe':23, 'Gode':23}, 
                'Bulehora': { 'Dilla':4, 'Yabello':3}, 
                'Konso': {'Arba Minchi':4, 'Yabello':3}, 
                'Basketo': { 'Arba Minchi':10, 'Bench Maji':5}, 
                'Humera': { 'Shire':8, 'Gondar':9},
                'Debarke': { 'Gondar':4, 'Shire':7},
                'Sekota': {'Alamata':6, 'Mekelle':9, 'Lalibella':6}, 
                'Babile': { 'Harar':2, 'Jigjiga':3,'Goba':28}, 
                'Kilbet Rasu': {'Fanti Rasu':6}, 
                'Mekelle': {'Alamata':5, 'Adigrat':4, 'Adwa':7, 'Sekota':9},
                'Gode': { 'Dollo':17, 'Kebri Dehar':5, 'Sof Oumer':23 }, 
                'Yabello': { 'Bulehora':3, 'Konso':3, 'Moyale':6},
                'Bench Maji': { 'Basketo':5}, 
                'Shire': { 'Axum':2, 'Humera':8, 'Debarke':7},               
                'Jigjiga': { 'Babile':3, 'Dega Habur':5}, 
                'Adigrat': { 'Mekelle':4, 'Adwa':4},
                'Adwa': { 'Mekelle':7, 'Axum':1, 'Adigrat':4},
                'Dollo':{'Gode':17,'Moyale':18},
                'Kebri Dehar': {'Gode':5, 'Dega Habur':6, 'Werdez':6}, 
                'Moyale': { 'Dollo':18,'Liben':11,'Yabello':6}, 
                'Axum': {'Shire':2, 'Adwa':1},
                'Dega Habur': {'Jigjiga':5, 'Kebri Dehar':6}, 
                'Werdez': { 'Kebri Dehar':6}}
                    
herustics_moyale = { 'Addis Ababa':26, 'Adama':23, 'Ambo':31,'Debre Berhan':31, 'Debre Markos':39, 'Matahara':26, 'Asella':22, 
                    'Batu':19, 'Wolkite':25,'Nekemte':39,'Debre Sina':33,'Finote Selam':42, 'Awash':27, 'Assasa':18,'Buta Jirra':21, 
                    'Shashamene':16,  'Worabe':22, 'Jimma':33, 'Hossana':21,'Bedelle':40, 'Gimbi':43, 'Kemise':40, 'Bahirdar':48, 
                    'Injibara':44, 'Chiro':31,'Gobi Rasu':32,'Dodolla':19, 'Hawassa':15, 'Bonga':33, 'Wolaita Sodo':17, 'Gore':46,  
                    'Dambidollo':49,'Assosa':51, 'Dessie':44, 'Metekel':59, 'Azezo':55, 'Debre Tabor':52, 'Dire Dawa':31, 'Samara':42,
                    'Robe':13, 'Dilla':12,'Dawro':23,  'Tepi':41, 'Mizan Teferi':37, 'Arba Minchi':13, 'Gambella':51,'Woldia':50, 'Gondar':56, 
                    'Metema':62, 'Lalibella':57,'Harar':35,'Fanti Rasu':49,'Alamata':53, 'Liben':11, 'Goba':40, 'Sof Oumer':45, 'Bulehora':8, 
                    'Konso':9,'Basketo':23,'Bench Maji':28,'Humera':65,'Debarke':60,'Sekota':59,'Babile':37, 'Kilbet Rasu':55, 
                    'Mekelle':58, 'Gode':35,  'Yabello':6, 'Shire':67, 'Adigrat':62,'Adwa':65, 'Dollo':18, 'Kebri Dehar':40, 
                    'Moyale':0, 'Axum':66, 'Jigjiga':40, 'Dega Habur':45, 'Kebri Dehar': 40, 'Werdez':4
        }

coffees_place_data = { 
                    "Addis Ababa": {"Ambo", "Buta Jirra", "Adama"},
                    "Ambo": {"Gedo", "Nekemte"},
                    "Buta Jirra": {"Worabe", "Wolkite"},
                    "Adama": {"Dire Dawa", "Mojo"},
                    "Gedo": {"Shambu", "Fincha"},
                    "Nekemte": {"Gimbi", "Limu"},
                    "Worabe": {"Hosana", "Durame"},
                    "Wolkite": {"Benchi Naji", "Tepi"},
                    "Mojo": {"Dilla", "Kaffa"},
                    "Dire Dawa": {"Chiro", "Harar"}
                }
terminal_utilities = ["Shambu", "Fincha", "Gimbi", "Limu", "Hosana", "Durame", "Benchi Naji", "Tepi", "Kaffa", "Dilla", "Chiro", "Harar"]

terminal = [4, 5, 8, 8, 6, 5, 5, 6, 7, 9, 6, 10]

graph_data1 =  {
                "Fincha": "Gedo",
                "Limu": "Nekemte",
                "Hosana": "Worabe",
                "Tepi": "Wolkite",
                "Dilla": "Mojo",
                "Harar": "Dire Dawa"
            }

graph_data2 = {
            "Gedo": "Ambo",
            "Worabe": "Buta Jirra",
            "Mojo": "Adama"
}